name: bar_wegielstwo_order
description: "Bar Węgielstwo Pro - kiosk zamawiania"
publish_to: 'none'
version: 0.0.2-alpha

environment:
  sdk: '^3.11.5'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  qr_flutter: ^4.1.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/